### ISSUE TITLE
GIC vCPU on tqma8xqp1gb

### ISSUE THREAD

**Issue by raduaron** [au-ts/libvmm#140] opened 2024-11-19 10:06 UTC
Hi!

We've been looking into running a virtual machine on the `tqma8xqp1gb` board based on the `simple` example and we got stuck at passing `gic_vcpu`. 

The issue is that the i.MX8X processor of this board does not have the CPU interface and the virtual CPU interface registers memory-mapped, but they are in system registers (more specifically [CBAR_EL1](https://developer.arm.com/documentation/100236/0100/register-descriptions/aarch64-system-registers/configuration-base-address-register--el1?lang=en)).
Seems like having these registers memory-mapped in only optional in GICv3, therefore they are missing from the [device tree](
https://github.com/seL4/seL4/blob/e995b646532e1667338830ed223da25cfbfe25fb/tools/dts/tqma8xqp1gb.dts#L147) and all other documentation we could find.

If anyone can provide some insight into how we could more forward it would be very much appreciated. 

Thanks!

**Comment by Ivan-Velickovic** [comment] 2024-11-19 10:56
Hmm, strange.

Have you tried reading the value of `CBAR_EL1`? The documentation says "Holds the physical base address of the memory-mapped GIC CPU interface registers". Is there an equivalent register that holds the vCPU interface registers?

The [device tree bindings in Linux for the GICv3](https://github.com/torvalds/linux/blob/158f238aa69d91ad74e535c73f552bd4b025109c/Documentation/devicetree/bindings/interrupt-controller/arm%2Cgic-v3.yaml#L72) say:
>    Specifies base physical address(s) and size of the GIC
      registers, in the following order:
      - GIC Distributor interface (GICD)
      - GIC Redistributors (GICR), one range per redistributor region
      - GIC CPU interface (GICC)
      - GIC Hypervisor interface (GICH)
      - GIC Virtual CPU interface (GICV)
      GICC, GICH and GICV are optional, but must be described if the CPUs
      support them

Implying that either the platform doesn't support them, or the device tree is wrong.

Is it certain that the `tqma8xqp1gb` is capable of hardware-supported virtualisation?

One easy way to find out without digging through the ARM manual may be to try boot the manufacturer provided Ubuntu or Debian etc and see if Linux can start a virtual machine. From Linux, you may also be able to list information about the interrupt-controller and where exactly they are in physical memory, although I don't know exactly how to do that myself.

**Comment by raduaron** [comment] 2024-11-19 12:26
1. The issue with reading `CBAR_EL1` is that it needs to be accessed from at least Exception Level 1. We hoped we can get around this somehow. Once we have the GIC CPU interface we can probably find the vCPU interface according to this mapping: https://developer.arm.com/documentation/100236/0100/functional-description/gic-cpu-interface/memory-map-for-the-gic-cpu-interface?lang=en.

2. Chapter 12.1 from the [GICv3 specification](https://developer.arm.com/documentation/ihi0069/latest/) specifies:

> • The Distributor, Redistributor, and ITS programming interfaces are always memory-mapped.
• The CPU interfaces for physical and virtual interrupt handling, and the virtual machine control interface used
by the hypervisor use:
— System register interfaces for the operation of GICv3 and GICv4.
— Memory-mapped interfaces for legacy operation.
Note
Support for legacy operation is optional.

We believe that statement from the device tree binding `..., but must be described if the CPUs support them` is referring to this legacy operation, not virtualization in general. 

3. The board's processor has Cortex A35 CPUs which support hardware virtualization according to [this](https://developer.arm.com/Processors/Cortex-A35).

4. We'll try tinkering around with the manufacturer Linux and try to access these registers, since we're assuming trying to do it from sel4/microkit wouldn't be so straight forward.

**Comment by Ivan-Velickovic** [comment] 2024-11-21 00:17
> We believe that statement from the device tree binding ..., but must be described if the CPUs support them is referring to this legacy operation, not virtualization in general.

Ah okay my bad I think I misunderstood then.

> We'll try tinkering around with the manufacturer Linux and try to access these registers, since we're assuming trying to do it from sel4/microkit wouldn't be so straight forward.

Yes, you would have to modify Microkit or seL4 since all PDs would run in EL0.

I added this patch to the Microkit bootloader:

```patch
diff --git a/loader/src/loader.c b/loader/src/loader.c
index 57f995e..0c8d85e 100644
--- a/loader/src/loader.c
+++ b/loader/src/loader.c
@@ -667,6 +667,11 @@ int main(void)
     configure_gicv2();
 #endif

+    puts("reading CBAR_EL1\n");
+    uint64_t val;
+    asm volatile("mrs %x0, S3_1_C15_C3_0" : "=r"(val) :: "cc");
+    puthex64(val);
+
 #ifdef ARCH_aarch64
     int r;
     enum el el;
```

and got `0x0000000052000000` as the value.

**Comment by Ivan-Velickovic** [comment] 2024-11-21 03:26
I was able to boot a Linux VM on the `tqma8xqp1gb`. The branch is here https://github.com/au-ts/libvmm/tree/tqma8xqp1gb, I based it of the MaaXBoard support since it's a similar SoC.

This line pops up in the Linux boot logs:
```
[    0.000000] CPU features: detected: GIC system register CPU interface
```

which makes sense now that I think about it. If the CPU/vCPU GIC interface isn't via MMIO, it means that the system registers must be virtualised by either the hardware or seL4 and so that's why things still work.

So I think that in this case there is no vCPU interface to map into the guest's memory. This is the first time I've encountered a board like this, so I'll make a note in the porting platform section in the manual about it.

I should note that while the VM gets into user-space, I wasn't able to get the buildroot terminal. Most likely due to some misconfiguration about the serial device:
```
[    1.418153] Warning: unable to open an initial console.
```

I should also note that change the loader link address in Microkit because of a bug in Microkit where large systems will overlap with the bootloader potentially and cause weird memory corruption issues:
```
diff --git a/build_sdk.py b/build_sdk.py
index 0dfda74..2c6fa10 100644
--- a/build_sdk.py
+++ b/build_sdk.py
@@ -88,7 +88,7 @@ SUPPORTED_BOARDS = (
         name="tqma8xqp1gb",
         arch=KernelArch.AARCH64,
         gcc_cpu="cortex-a35",
-        loader_link_address=0x80280000,
+        loader_link_address=0xa0000000,
         kernel_options={
             "KernelPlatform": "tqma8xqp1gb",
             "KernelIsMCS": True,
```

sorry about this, I'll add extra error checking/asserts such that this is caused by built-time, and fix the underlying issue that allows this to happen.

**Comment by Ivan-Velickovic** [comment] 2024-11-21 04:03
> This is the first time I've encountered a board like this, so I'll make a note in the porting platform section in the manual about it.

Done in https://github.com/au-ts/libvmm/commit/a996382581b9dbb7f067b25f312e87264c7b8ace.

**Comment by raduaron** [comment] 2024-11-22 10:24
Thanks a lot for all the help on this! We are trying to have the console working as well.
We saw the [`linux.dts`](https://github.com/au-ts/libvmm/commit/f4a4d365b17ddb555300a40c58d4406822b1c265#diff-46882cf3e21d31a33ac6c362e29255dba182b504a50a41749e90413a08ab7728) you are using is quite different from the [original](https://github.com/seL4/seL4/blob/master/tools/dts/tqma8xqp1gb.dts). We were wondering if those modifications are handpicked by you or is it somewhere you got all this from, since it seems that Linux boots fine with the original one as well?

**Comment by Ivan-Velickovic** [comment] 2024-11-24 00:54
The `linux.dts` is straight from Linux, it's most likely different since the seL4 one is also from Linux but from an older version. seL4 only needs a few devices and very little information from the DTS and so doesn't need to be kept up-to-date. I would recommend using a device tree from the version of the Linux kernel you are using the VM with.

My understanding is that the DTS that is in the seL4 repository is just for the kernel itself to get information about the platform rather than the source of truth for the platform for *users* of seL4 as well.

All the changes I had to make to get the VM working are in `overlay.dts` (e.g lowering amount of RAM, custom `chosen` node etc).

For debugging the console issue, make sure my `bootargs` line in `overlay.dts` is correct, especially the `console=` part. The `Warning: unable to open an initial console.` indicates that maybe something is wrong with the buildroot initramfs as well, so I would check that too.

I think this issue is now resolved so I'm going to close it. Feel free to re-open or post more issues if you run into anything else.

**Closed by Ivan-Velickovic** 2024-11-24 00:54 UTC
